use_frameworks!

platform :ios, '9.0'

target 'ZJHCommon_Example' do
  pod 'ZJHCommon', :path => '../'

  target 'ZJHCommon_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
